### ISSUE TITLE
Converting NULL to string is unsupported : Error while backup

### ISSUE THREAD

**Issue by eahlys** [tagatac/bagoup#13]
Hello !
I'm encountering a fatal error when I run bagoup :

`~# bagoup --db-path=chat.db
2022/07/15 12:03:41 0 messages successfully exported to folder "messages-export"
2022/07/15 12:03:41 ERROR: export chats: get attachment paths: get path for attachment 25 to message 414: read data for attachment ID 25: sql: Scan error on column index 0, name "filename": converting NULL to string is unsupported`

This happens wether I specify the chat.db path (previously copied in another location) or when I just use the default path (while granting full disk access to my terminal emulator)

I think that some attachments are broken ?

**Comment by tagatac** [comment]
Thanks for the issue! I think I know how to fix this. I'll let you know when I have something for you to test probably later today.

**Comment by tagatac** [comment]
@ptnr, @richardsprague, this should be fixed on the `main` branch. Instead of failing, you should get a warning for missing attachments. Can one of you clone, build and test before I cut a release?

**Comment by tagatac** [comment]
v2.0.3 has this fix. It's available via homebrew.
