### ISSUE TITLE
file name too long error for contacts with multiple phone numbers / emails

### ISSUE THREAD

**Issue by rchen19** [tagatac/bagoup#32]
**Describe the bug**
When the command is run without `--separate-chats` flag, it tries to merge chat history from multiple phone numbers and emails under the same contacts, and it creates a `.txt` file by naming it with the concatenation of all those phone numbers and emails, and this could create a file name exceeds the length limit.

Probably not many people will have this problem though.

**To Reproduce**
 just run the commands without `--separate-chats`, and if you have a contacts with more than 4 phone numbers and more than 4 emails, you will likely see "file name too long" error.

**Expected behavior**
Should truncate the file name if too long.

**Environment (please complete the following information):**
 - OS: macOS 12.6
 - Version 2.1.2 Darwin/arm64

**Comment by tagatac** [comment]
- @rchen19 are you able to provide the full error message (with actual email addresses and phone numbers redacted)?
- What is the limit you're seeing? 255 characters?
- Does the limit include the full path or just the filename?

**Comment by rchen19** [comment]
Sorry it took a while. I am attaching the full error message below, redacting some private information, such as phone numbers and emails:


`2022/09/21 22:48:54 ERROR: export chats: create file "/Users/***/Downloads/messages_export1/Jim Smith/iMessage;-;johnsmith02@163.com;;;SMS;-;johnsmith@icloud.com;;;iMessage;-;johnsmith@icloud.com;;;iMessage;-;john.smith@gmail.com;;;iMessage;-;+12********;;;iMessage;-;+8************;;;SMS;-;john.smith@gmail.com;;;iMessage;-;+13********;;;SMS;-;+13********;;;iMessage;-;johnsmith02@icloud.com;;;SMS;-;johnsmith02@icloud.com.txt": open /Users/***/Downloads/messages_export1/Jim Smith/iMessage;-;johnsmith02@163.com;;;SMS;-;johnsmith@icloud.com;;;iMessage;-;johnsmith@icloud.com;;;iMessage;-;john.smith@gmail.com;;;iMessage;-;+12********;;;iMessage;-;+8************;;;SMS;-;john.smith@gmail.com;;;iMessage;-;+13********;;;SMS;-;+13********;;;iMessage;-;johnsmith02@icloud.com;;;SMS;-;johnsmith02@icloud.com.txt: file name too long`
