### ISSUE TITLE
Exporting attachments using directory structure such as Apple iWork files produces error and terminates output

### ISSUE THREAD

**Issue by oneofthedamons** [tagatac/bagoup#35]
**Describe the bug**
Using `-a` to export attachments which are directories (such as Apple iWork documents) produces an error which halts execution

**To Reproduce**
1. Send an Apple Pages file as an attachment to an iMessage
2. Execute `bagoup -c example.vcf -a`
3. A series of WARN messages are logged and then:
```
BAGOUP RESULTS:
bagoup version: 2.1.2 Darwin/x86_64
Export folder: "messages-export"
Export files written: 317
Chats exported: 345
Messages exported: 6781
Attachments copied: 866
	image/heic: 7
	image/jpeg: 500
	image/tiff: 14
	video/quicktime: 4
	application/pdf: 4
	text/x-vlocation: 3
	text/vcard: 2
	video/3gpp: 1
	image/png: 56
	application/octet-stream: 271
	image/gif: 2
	audio/amr: 2
Attachments referenced or embedded: 872
	application/pdf: 4
	image/heic: 7
	image/png: 56
	application/octet-stream: 273
	image/tiff: 14
	video/quicktime: 4
	text/x-vlocation: 3
	image/jpeg: 504
	image/gif: 2
	audio/amr: 2
	text/vcard: 2
	video/3gpp: 1
Attachments embedded: 0
Attachments missing (see warnings above): 6
HEIC conversions completed: 0
HEIC conversions failed (see warnings above): 0
Time elapsed: 5.305668045s
```
4. The error is then shown:
```
ERROR: export chats: chat file "messages-export/<contact>/iMessage;-;example@icloud.com.txt" - message <message_id>: copy attachment "/Users/$USERNAME/Library/Messages/Attachments/<path/to/attachment>/example.pages" to "messages-export/<contact_name>/attachments": read /Users/$USERNAME/Library/Messages/Attachments/<path/to/attachment>/example.pages: is a directory
```
5. `bagoup` terminates with the remaining messages from that contact and subsequent contacts (alphabetically) not exported

**Expected behavior**
- Attachments using a directory structure should be created in the export path using the same directory structure
- The error should not be considered fatal; execution should continue from the next message

**Environment (please complete the following information):**
 - OS: [e.g. Mac OS 12.5] **MacOS 12.6**
 - Version [e.g. v2.0.4] (obtain with `bagoup --version`) `bagoup version 2.1.2 Darwin/x86_64`

**Comment by tagatac** [comment]
Ah yes, the infamous folders disguised as files in Mac OS. Thanks for the report.

**Comment by oneofthedamons** [comment]
Thanks, this seems to have done the trick!
