### ISSUE TITLE
Renaming attachment files does not update the text file

### ISSUE THREAD

**Issue by rchen19** [tagatac/bagoup#36]
**Describe the bug**
When bagoup is run with `-a` flag, and when a chat history contains more than one attachment files with the same file name, it will rename the files with the same name except the first one, in order to copy the into the same subdirectory. However the reference to that file name in the text transcript is not update. 

For example, when you see files being renames:

```
2022/09/23 14:05:35 WARN: copy "/Users/***/Library/Messages/Attachments/da/10/at_1_26E0DB19-890A-4C9E-874A-397735C7B9E5/Image-1.jpeg" to "/Users/***/Downloads/messages_export1/John Smith/attachments" - "Image-1.jpeg" already exists; using "Image-1-2.jpeg" instead
```

You are still seen multiple references to in the transcript:

```
[2020-11-05 17:59:13] Me: I really hope *****
<attached: Image-1.jpeg>
<attached: Image-1.jpeg>
[2020-11-05 17:59:27] John: I think it’s coming 
```

**To Reproduce**
Just run the command with `-a`, and if you have duplicated file names in the same conversation, this behavior will appear.

**Expected behavior**
The reference in the transcript text should also be updated when the name of the file referred to is changed

**Environment (please complete the following information):**
- OS: macOS 12.6
- Version 2.1.2 Darwin/arm64

**Comment by tagatac** [comment]
I actually did this on purpose to keep the filenames in the transcript true to the original filenames. However, in retrospect, I tend to agree with you that being able to identify the referenced attachment is more important than preserving the original filename.
