### ISSUE TITLE
Is there a way to export the conversation from just one particular contact?

### ISSUE THREAD

**Issue by hounsellal** [tagatac/bagoup#54]
**Is your feature request related to a problem? Please describe.**
Ability to export conversation from just one contact rather than entire iMessages

**Describe the solution you'd like**
add a flag:
--limit-to-contact="+15551124456"

**Describe alternatives you've considered**
Right now I have to export everything and then delete all but the contact I want. Takes a long time

**Additional context**
n/a

**Comment by tagatac** [comment]
This isn't possible at the moment, but I would find this useful myself for debugging. Thanks for the issue!

**Comment by tagatac** [comment]
@hounsellal I created a branch https://github.com/tagatac/bagoup/tree/entity-filter with a quick and dirty solution. Want to try it out before I add some tests and merge?
```
$ git clone https://github.com/tagatac/bagoup.git
$ cd bagoup
$ git checkout entity-filter
$ make
$ bin/bagoup --help
$ bin/bagoup --entity "+15551124456"
```

**Comment by tagatac** [comment]
@hounsellal sorry it took so long, but I've just cut a new version (v2.4.5 available via homebrew now) with this update. Check it out and LMK if it solves your use case when you get a chance.
