### ISSUE TITLE
Some conversations missing from export

### ISSUE THREAD

**Issue by tagatac** [tagatac/bagoup#62]
the program doesn’t seem to have exported all the conversations I’ve had, specifically group texts and messages from specific people I’ve texted plenty of times. I reran the command a couple times and then another contact’s convo thread finally showed up, but there are still some other convos missing. Don’t know why this would be?

_Originally posted by @sav5000 in https://github.com/tagatac/bagoup/discussions/49#discussioncomment-10563590_

**Comment by tagatac** [comment]
@sav5000, after completing successfully, bagoup should print a summary of the export like this:
```
2024/09/09 11:45:53 BAGOUP RESULTS:
bagoup version: 2.4.6 Darwin/arm64
Export folder: "messages-export"
Export files written: 197
Chats exported: 202
Valid messages exported: 33653
Invalid messages exported (see warnings above): 43
Attachments copied: 0
Attachments referenced or embedded: 2346
	image/tiff: 4
	image/png: 91
	text/x-vlocation: 8
	video/quicktime: 45
	text/vcard: 8
	image/heic-sequence: 1
	video/3gpp: 2
	image/heic: 681
	application/octet-stream: 1209
	image/jpeg: 240
	image/gif: 51
	application/pdf: 5
	audio/x-m4a: 1
Attachments embedded: 0
Attachments missing (see warnings above): 6
HEIC conversions completed: 0
HEIC conversions failed (see warnings above): 0
Time elapsed: 29.211126875s
```

Can you paste the summary for a run where some conversations are missing?

**Comment by sav5000** [comment]
Oh, no summary like that was provided, even after running the program multiple times. Just to make sure, this is the command I'm using, does it look right? Thank you again for your help and patience! 
bagoup  --export-path messages-export-pdf --pdf  --include-ppa --preserve-paths

**Comment by tagatac** [comment]
Based on this [comment](https://github.com/tagatac/bagoup/issues/63#issuecomment-2350767791), I think this is resolved now. Please re-open if it isn't.
