### ISSUE TITLE
Option to merge iMessage files for same contact

### ISSUE THREAD

**Issue by vwkd** [tagatac/bagoup#8]
The `-c` option is great, as it bundles iMessages and SMS for the same contact in one folder.

Unfortunately, iMessage allows to change the sender address. The contact may use their phone number, or may use any one of their email addresses associated with the Apple ID. This leads to multiple `iMessage;-;SENDER_ADDRESS.txt` files for the same contact, if they ever changed their sender address.

It would be great if there was an option to combine those multiple `iMessage;-;SENDER_ADDRESS.txt` files for the same contact.

**Comment by tagatac** [comment]
This is a great idea, and worth tackling before image export IMO! Thanks for the issue!

**Comment by tagatac** [comment]
@vwkd can you try out #10?
