### ISSUE TITLE
Order messages by date time

### ISSUE THREAD

**Issue by vwkd** [tagatac/bagoup#9]
It seems that the messages are not ordered, but extracted as is from the database?

For older messages in an iMessage file `iMessage;-;SENDER_ADDRESS.txt`, the history seems to be out of order. It seems that at least the years are "somewhat ordered" but not consistently. I'm unsure what ordering this is.

Also I noticed that the order for iMessage files whose sender address is an email is roughly descending (above new, bottom old), while for a sender address that's a phone number it's the opposite, roughly ascending (above old, bottom new).

It would probably make sense to order them, before writing the file. Ideally, this would also work well together with #8 which merges iMessage files of the same contact with different sender addresses.

**Comment by tagatac** [comment]
@vwkd I'm not sure I've seen this. Are you able to provide a chat.db that displays this behavior?

**Comment by lilynet336** [comment]
I am also seeing this issue. I'm not really comfortable providing my database file, but older exported messages are definitely out of order.

**Comment by tagatac** [comment]
Thanks, @bobbyl140. Can either you or @vwkd provide a benign chat file that displays out of order messages. chat.db is even better, but a chat file would be helpful. Feel free to email it to david@tagatac.net if you are not comfortable posting it.

I see that I am [depending on the ordering of messages in the database](https://github.com/tagatac/bagoup/blob/35b96e61904813ba2b41329b0307264d5a708464/main.go#L147-L152), which is probably the issue, but I would like to see at least one example of a bad ordering.

**Comment by lilynet336** [comment]
I don't really feel comfortable providing the actual messages, so I took a screenshot of the dates in one of the files. If that doesn't help I can redact the private info from the file and upload the whole thing. 
![Screen Shot 2022-01-17 at 2 45 51 PM](https://user-images.githubusercontent.com/61990607/149829370-d0fee79c-7909-492f-bf87-a559c53e2b3f.png)

**Comment by lilynet336** [comment]
My apologies, that wasn't a good example. Let me find a better one.

**Comment by lilynet336** [comment]
I used `grep` to make a file with all the dates minus the message content, same order as the backup file. Let me know if you would like another example.
[times.txt](https://github.com/tagatac/bagoup/files/7884401/times.txt)

**Comment by tagatac** [comment]
Thanks, I did actually find an example in my own database. Thanks again for the bug and updates.

**Comment by lilynet336** [comment]
Glad to help. I also wanted to compliment your project, it’s a nice feature that Apple has not provided.

**Comment by tagatac** [comment]
It should be fixed on the master branch. Want to try it out before I cut a release?

**Comment by lilynet336** [comment]
Please. I’ll go do that now and report back with the results.

**Comment by lilynet336** [comment]
It appears to be working. I'd say it's good for release. Thank you!

**Comment by tagatac** [comment]
Released and homebrew formula updated.
